name: Testing Pull request mechanism in develop branch

on:

  pull_request:
    branches: [ develop ]
jobs:
  build:

    name: Building Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]

    env:
      MODE: "dev"
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: testing
        run: |
          echo "Testing"